### ISSUE TITLE
KEN_CustomizeGauge.js と VisuStella プラグインを併用する場合の問題

### ISSUE THREAD

**Issue by gejiziliao** [t-kendama/RPGMakerMZ#1]
KEN_CustomizeGauge.js を VisuMZ_1_BattleCore.js および VisuMZ_1_MainMenuCore.js と併用した場合、設定した HP、MP、TP が無効になる問題を修正してください。

**Comment by t-kendama** [comment]
他プラグインの併用で引き起こされる問題は修正が困難のため対応できません。
ご了承ください。
